### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by xinjiboy1234** [dustinkredmond/SharePointAPI#4]
when i  try to  get token , there was response message as below . 

<psf:internalerror>
    <psf:code>0x80048821</psf:code>
    <psf:text>AADSTS50126: Error validating credentials due to invalid username or password.</psf:text>
</psf:internalerror>

**Comment by dustinkredmond** [comment]
This is likely due to incorrect username or password being supplied. Make sure you verify that your username is using the domain prefix if you're trying to access a company site. E.g. username should be like `MyCompany\MyUsername`.

**Comment by xinjiboy1234** [comment]
> This is likely due to incorrect username or password being supplied. Make sure you verify that your username is using the domain prefix if you're trying to access a company site. E.g. username should be like `MyCompany\MyUsername`.

thanks a lot , now i got another error, 
<psf:reqstatus>0x8004882c</psf:reqstatus>
  <psf:errorstatus>0x80045b00</psf:errorstatus>

did you know what is 0x80045b00 meaning?, i do not have any idea of this, even search on the network so long time.

**Comment by xinjiboy1234** [comment]
I think it it this error , I have to register the app in azure,
